### PR TITLE
Add dark mode support

### LINKED ISSUE #88: Dark mode support
I saw in the code that there is currently some support for a dark mode version of the app.
Unfortunately, I know this is currently not implemented. Could a switch be added to toggle between light and dark modes?
As a bonus, making it follow system dark more preferences should also be an option.

Relevant code: https://github.com/stayawayinesctec/stayaway-app/blob/546576e7903f4ca6c732d62e679eca9b120bfe43/src/app/contexts/Theme/index.js#L25
https://github.com/stayawayinesctec/stayaway-app/blob/ff885b9c1a5b44e8c03e5928fcf9ec31215907fa/src/app/common/theme/index.js

I could also submit a PR if needed.

### PR DESCRIPTION
**Pull request by diogotcorreia**
This PR adds dark mode support to the app, just as it'd be expected. Closes #88.

Notable changes:
 - There is no dark mode toggle, the app follows the system theme (edited `Root/index.js` for that change).
 - Some colors were added to make this change possible.
 - The background color is `#202124`.
 - Some images were inverted to have better visibility while in dark mode.

Please note that this was only tested on Android.

Feel free to ask for improvements.

<details>
  <summary>Screenshots</summary>

Screenshot_20201024-105743
Screenshot_20201024-105751
Screenshot_20201024-105934
Screenshot_20201024-114208
Screenshot_20201024-114223
Screenshot_20201024-114227
Screenshot_20201024-114233
Screenshot_20201024-114249
Screenshot_20201024-114253
</details>

### CODE REVIEW

**Review by RiscadoA — APPROVED** [review]

**Review by imnotender — APPROVED** [review]

**Comment by fmaia** [comment]
Hi @diogotcorreia, thank you for the PR. 
There is a design team in charge of the color schemes for the app and we will run this by them. We will also check all the images to get official "dark mode-compliant" versions.

**Comment by diogotcorreia** [comment]
@fmaia Hi, thanks for your reply!

I see that there are some conflicts that need to be solved. I'll work on that this weekend.

> There is a design team in charge of the color schemes for the app

Alright, feel free to push to the PR branch if you need to edit the colors.

Additionally, would you be interested in me adding a theme toggle in the settings? Right now it only follows the system theme, but some people might prefer to change it manually (or are on devices that don't support system-wide dark mode).

**Comment by diogotcorreia** [comment]
@fmaia Just added a theme selector in the settings. Strings are obviously translated in the `i18n` files, as expected.
Screenshot_20201031-112707

**Comment by RGarrido03** [comment]
Hi everyone! I've been following this app's development since the the creation of this repo and so I wanna congratulate you all for your amazing work!
Regarding dark mode, why isn't the main color black but gray? I personally think the color hex #000000 looks really good on (AM)OLED displays and it can also save some battery

**Comment by diogotcorreia** [comment]
@RGarrido03 
Thanks for your interest in this PR.  
I've decided to use a darker shade of gray instead of black because it has better contrast. I also prefer true black myself, but since the app relies on shadows for some contrast, I decided to not use it.

Anyway, @fmaia said the design team would check this PR, so they might have other options in the colors.

**Comment by fmaia** [comment]
> @RGarrido03
> Thanks for your interest in this PR.
> I've decided to use a darker shade of gray instead of black because it has better contrast. I also prefer true black myself, but since the app relies on shadows for some contrast, I decided to not use it.
> 
> Anyway, @fmaia said the design team would check this PR, so they might have other options in the colors.

yes, @diogotcorreia and @RGarrido03, I'm waiting for feedback on this. Thanks for the contribution. Once we get this out it will be useful for many people!

**Comment by diogotcorreia** [comment]
@fmaia Hi!
Any updates on this?

**Comment by djcouto** [comment]
Hi @diogotcorreia,

The dark mode the design team gave us was not so different from the one you implement. There are just a few more extra things that they ask us to do, but we will do that later so that this PR does not become gigantic.

In order to get this merged, could you:
- change the colour **darkModeBlack** to `#121212`.
- add the [official dark logos](https://we.tl/t-cPcWCoiIb9). Note that not everyone has an official dark logo and for those, we will use the original one.

Really nice work btw :+1:

**Comment by diogotcorreia** [comment]
@djcouto Ready to merge! 😁

**Review by djcouto — APPROVED** [review]

**Pull request merged**
