### PR TITLE
Changed date format to dd/mm/yyyy

### PR DESCRIPTION
**Pull request by suskind**
The date should be formatted as `dd/mm/yyyy`. With the `d.m.yyyy` format it looks like the app's version

### CODE REVIEW

**Comment by palminha** [comment]
you are right... now looking at it more carefully it's a date... 👍

**Comment by gerdemb** [comment]
Perhaps this should be a localized date or at least made unambiguous? dd/mm/yyyy can be confused with mm/dd/yyyy although in this case the date displayed should generally be close to the current date reducing the chance of confusion...

**Comment by djcouto** [comment]
Hi @suskind.

We agree on changing the date format. Could you please resolve the conflicts and also change the format on the `src/settings/components/Debug.js` file?

Thank you

**Comment by suskind** [comment]
@djcouto  ok, done.

**Review by djcouto — APPROVED** [review]
Thank you, it will be on next release 👍

**Pull request merged**
